export const COLORS: string[] = [
    'red-dark',
    'red',
    'red-light',
    'pink-dark',
    'pink',
    'pink-light',
    'purple-dark',
    'purple',
    'purple-light',
    'deep-purple-dark',
    'deep-purple',
    'deep-purple-light',
    'indigo-dark',
    'indigo',
    'indigo-light',
    'violet-dark',
    'violet',
    'violet-light',
    'blue-dark',
    'blue',
    'blue-light',
    'light-blue-dark',
    'light-blue',
    'light-blue-light',
    'cyan-dark',
    'cyan',
    'cyan-light',
    'teal-dark',
    'teal',
    'teal-light',
    'green-dark',
    'green',
    'green-light',
    'light-green-dark',
    'light-green',
    'light-green-light',
    'lime-dark',
    'lime',
    'lime-light',
    'yellow-dark',
    'yellow',
    'yellow-light',
    'amber-dark',
    'amber',
    'amber-light',
    'orange-dark',
    'orange',
    'orange-light',
    'deep-orange-dark',
    'deep-orange',
    'deep-orange-light',
    'brown-dark',
    'brown',
    'brown-light',
    'grey-dark',
    'grey',
    'grey-light',
    'blue-grey-dark',
    'blue-grey',
    'blue-grey-light',
    'white-dark',
    'white',
    'white-light',
    'black-dark',
    'black',
    'black-light',
];

// export const COLORS: string[] = [
//     'violet-dark',
//     'violet',
//     'violet-light',
//     'blue-dark',
//     'blue',
//     'blue-light',
//     'cyan-dark',
//     'cyan',
//     'cyan-light',
//     'green-dark',
//     'green',
//     'green-light',
//     'yellow-dark',
//     'yellow',
//     'yellow-light',
//     'orange-dark',
//     'orange',
//     'orange-light',
//     'red-dark',
//     'red',
//     'red-light',
//     'pink-dark',
//     'pink',
//     'pink-light',
//     'black-dark',
//     'black',
//     'black-light',
//     'grey-dark',
//     'grey',
//     'grey-light',
//     'white-dark',
//     'white',
//     'white-light'
// ];
