/* Models */
import { Icon } from "../models/icon.model";

export const ICONS: Icon[] = [
    { name: 'adobe after effects', icon: 'logo-adobe-after-effects' },
    { name: 'adobe audition', icon: 'logo-adobe-audition' },
    { name: 'adobe creative cloud', icon: 'logo-adobe-creative-cloud' },
    { name: 'adobe dreamweaver', icon: 'logo-adobe-dreamweaver' },
    { name: 'adobe illustrator', icon: 'logo-adobe-illustrator' },
    { name: 'adobe lightroom', icon: 'logo-adobe-lightroom' },
    { name: 'adobe photoshop', icon: 'logo-adobe-photoshop' },
    { name: 'adobe premiere', icon: 'logo-adobe-premiere' },
    { name: 'adobe xd', icon: 'logo-adobe-xd' },
    { name: 'adobe', icon: 'logo-adobe' },
    { name: 'amazon prime', icon: 'logo-amazon-prime' },
    { name: 'apple arcade', icon: 'logo-apple-arcade' },
    { name: 'apple fitness', icon: 'logo-apple-fitness' },
    { name: 'apple music', icon: 'logo-apple-music' },
    { name: 'apple podcasts', icon: 'logo-apple-podcasts' },
    { name: 'apple tv', icon: 'logo-apple-tv' },
    { name: 'apple', icon: 'logo-apple' },
    { name: 'audible', icon: 'logo-audible' },
    { name: 'crunchyroll', icon: 'logo-crunchyroll' },
    { name: 'dazn', icon: 'logo-dazn' },
    { name: 'deezer', icon: 'logo-deezer' },
    { name: 'disney-plus', icon: 'logo-disney' },
    { name: 'ea', icon: 'logo-ea' },
    { name: 'google play', icon: 'logo-google-play' },
    { name: 'google podcasts', icon: 'logo-google-podcasts' },
    { name: 'google', icon: 'logo-google' },
    { name: 'hbo max', icon: 'logo-hbo-max' },
    { name: 'hbo', icon: 'logo-hbo' },
    { name: 'icloud', icon: 'logo-icloud' },
    { name: 'movistar', icon: 'logo-movistar' },
    { name: 'netflix', icon: 'logo-netflix' },
    { name: 'nintendo switch', icon: 'logo-nintendo-switch' },
    { name: 'other', icon: 'card-outline' },
    { name: 'patreon', icon: 'logo-patreon' },
    { name: 'paypal', icon: 'logo-paypal' },
    { name: 'playstation', icon: 'logo-playstation' },
    { name: 'podcasts', icon: 'logo-podcasts' },
    { name: 'spotify', icon: 'logo-spotify' },
    { name: 'tidal', icon: 'logo-tidal' },
    { name: 'twitch', icon: 'logo-twitch' },
    { name: 'vimeo', icon: 'logo-vimeo' },
    { name: 'vodafone', icon: 'logo-vodafone' },
    { name: 'xbox', icon: 'logo-xbox' },
    { name: 'youtube', icon: 'logo-youtube' }
];
